### ISSUE TITLE
Out top-level option people links to /team

### ISSUE THREAD

**Issue by zvonimir** [soarlab/soarlab.github.io#15]
While we renamed the top level option to people (instead of team) its url is still pointing to team. It would be good to update that to people as well.

**Comment by rospoly** [comment]
Now the url contains "people" instad of "team"
https://github.com/soarlab/soarlab.github.io/commit/44b5ff424e91618028d52fe8853d91185eddcc6b

**Comment by zvonimir** [comment]
We will not fix this one since it is too complicated. Instead we will rename "people" into "team" at the top level.
