### ISSUE TITLE
Cleaning up posts

### ISSUE THREAD

**Issue by zvonimir** [soarlab/soarlab.github.io#3]
The same goes for the `_posts` folder. We should remove all posts not belonging to us.

**Comment by rospoly** [comment]
Our website does not have a news section (our news section is made of Twitter posts). 
None of the news belong to us. I remove all of them.
https://github.com/soarlab/soarlab.github.io/commit/591bb3bd87cb976762202764502c895796678306

**Comment by zvonimir** [comment]
This is done.
