### ISSUE TITLE
Rename PDFs into papers

### ISSUE THREAD

**Issue by zvonimir** [soarlab/soarlab.github.io#5]
I don't particularly like capital letters in URLs. So I would prefer that we rename the folder with papers as `papers` instead of `PDFs`. Thanks!

**Comment by rospoly** [comment]
"PDFs" folder becomes "papers"
https://github.com/soarlab/soarlab.github.io/commit/88a7f15a528b0ce76233effd86f8bebc003c59c8

**Comment by zvonimir** [comment]
This is done.
